### ISSUE TITLE
Support for the latest model formats

### ISSUE THREAD

**Issue by okpatil4u** [vv9k/AIrtifex#3]
Apparently new types of GGJT formats have landed in llama.cpp and for llama-rs it's a [breaking change ](https://github.com/rustformers/llm/issues/252)as well. Will AIrtifex support this change out of the box ? Or are some changes required ?

**Comment by vv9k** [comment]
I created a PR that updates `llama-rs` to `llm` and adds support for all model formats. I only tested it with LLaMa model so there still might be some things missing. Will merge it soon.

**Comment by okpatil4u** [comment]
Thanks @vv9k.

**Comment by vv9k** [comment]
Please create an issue if you find any problems with running other model formats ;)
